### ISSUE TITLE
Magento 2 getting Issue on product page in admin.

### ISSUE THREAD

**Issue by allinvinod** [magearray/magento2-price-match#1]
I am using your extension. after installing the extension, I am getting below error:

1 exception(s):
Exception #0 (MagentoFrameworkExceptionLocalizedException): The configuration parameter "componentType" is a required for "lower-price-options" component.

Exception #0 (MagentoFrameworkExceptionLocalizedException): The configuration parameter "componentType" is a required for "lower-price-options" component.
#0 //vendor/magento/framework/View/Element/UiComponentFactory.php(404): MagentoFrameworkViewElementUiComponentFactory->mergeMetadataItem(Array, Array, false)
#1 //vendor/magento/framework/View/Element/UiComponentFactory.php(313): MagentoFrameworkViewElementUiComponentFactory->mergeMetadataItem(Array, Array, false)
#2 //vendor/magento/framework/View/Element/UiComponentFactory.php(216): MagentoFrameworkViewElementUiComponentFactory->mergeMetadata('product_form', Array, false)
#3 //vendor/magento/framework/View/Layout/Generator/UiComponent.php(135): MagentoFrameworkViewElementUiComponentFactory->create('product_form', NULL, Array)
#4 //vendor/magento/framework/View/Layout/Generator/UiComponent.php(97): MagentoFrameworkViewLayoutGeneratorUiComponent->generateComponent(Object(MagentoFrameworkViewLayoutDataStructure), 'product_form', Array, Object(MagentoFrameworkViewLayoutInterceptor))
#5 //vendor/magento/framework/View/Layout/GeneratorPool.php(80): MagentoFrameworkViewLayoutGeneratorUiComponent->process(Object(MagentoFrameworkViewLayoutReaderContext), Object(MagentoFrameworkViewLayoutGeneratorContext))
#6 //vendor/magento/framework/View/Layout.php(344): MagentoFrameworkViewLayoutGeneratorPool->process(Object(MagentoFrameworkViewLayoutReaderContext), Object(MagentoFrameworkViewLayoutGeneratorContext))
#7 //generated/code/Magento/Framework/View/Layout/Interceptor.php(89): MagentoFrameworkViewLayout->generateElements()
#8 //vendor/magento/framework/View/Layout/Builder.php(129): MagentoFrameworkViewLayoutInterceptor->generateElements()
#9 //vendor/magento/framework/View/Page/Builder.php(55): MagentoFrameworkViewLayoutBuilder->generateLayoutBlocks()
#10 //vendor/magento/framework/View/Layout/Builder.php(65): MagentoFrameworkViewPageBuilder->generateLayoutBlocks()
#11 //vendor/magento/framework/View/Layout.php(254): MagentoFrameworkViewLayoutBuilder->build()
#12 //vendor/magento/framework/View/Layout.php(875): MagentoFrameworkViewLayout->build()
#13 //generated/code/Magento/Framework/View/Layout/Interceptor.php(414): MagentoFrameworkViewLayout->getBlock('menu')
#14 //vendor/magento/module-backend/Model/View/Result/Page.php(26): MagentoFrameworkViewLayoutInterceptor->getBlock('menu')
#15 //generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(24): MagentoBackendModelViewResultPage->setActiveMenu('Magento_Catalog...')
#16 //vendor/magento/module-catalog/Controller/Adminhtml/Product/Edit.php(69): MagentoBackendModelViewResultPageInterceptor->setActiveMenu('Magento_Catalog...')
#17 //generated/code/Magento/Catalog/Controller/Adminhtml/Product/Edit/Interceptor.php(24): MagentoCatalogControllerAdminhtmlProductEdit->execute()
#18 //vendor/magento/framework/App/Action/Action.php(107): MagentoCatalogControllerAdminhtmlProductEditInterceptor->execute()
#19 //vendor/magento/module-backend/App/AbstractAction.php(229): MagentoFrameworkAppActionAction->dispatch(Object(MagentoFrameworkAppRequestHttp))
#20 //vendor/magento/framework/Interception/Interceptor.php(58): MagentoBackendAppAbstractAction->dispatch(Object(MagentoFrameworkAppRequestHttp))
#21 //vendor/magento/framework/Interception/Interceptor.php(138): MagentoCatalogControllerAdminhtmlProductEditInterceptor->___callParent('dispatch', Array)
#22 //vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): MagentoCatalogControllerAdminhtmlProductEditInterceptor->MagentoFrameworkInterception{closure}(Object(MagentoFrameworkAppRequestHttp))

Can you please help to fix the issue?

**Comment by magearray** [comment]
Please raise the support ticket at https://www.magearray.com/support/
